FROM node:16-alpine AS visual-editor-builder

ARG GIT_BRANCH
ARG GIT_REVISION

WORKDIR /visual-editor

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY public ./public
COPY src ./src

ENV NODE_ENV=production
ENV NODE_OPTIONS=--max_old_space_size=4096
ENV REACT_APP_LANGUAGES="fr|French|fr_FR,en|British English|en_GB,de|German|de_DE"
ENV REACT_APP_DEFAULT_LANGUAGE=fr_FR
ENV REACT_APP_MILLER_CLIENT_ID=b7X9djWuMXK5WZBCNINieUFyQfnFkIPqgf3MsaN5
ENV REACT_APP_VISUAL_EDITOR_GIT_BRANCH=${GIT_BRANCH}
ENV REACT_APP_VISUAL_EDITOR_GIT_REVISION=${GIT_REVISION}
ENV REACT_APP_EDITOR_BASENAME=/editor
ENV PUBLIC_URL=/editor
ENV REACT_APP_MAPBOX_STYLE_URL=mapbox://styles/mapbox/streets-v11
ENV REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiZGFuaWVsZWd1aWRvdW5pIiwiYSI6ImNsMmVyOW5vazAyOXczaW8zYmJnOGczeWIifQ.R8HvtSP3S8gTlpkUeWq-BA
ENV REACT_APP_FRONTEND_URL=https://ww2.lu
ENV REACT_APP_DOCUMENT_SCHEMA=/miller-static/schema/document/payload.json
ENV REACT_APP_CONTENT_ACCEPTED_FILES=image/jpeg,image/png,application/pdf
ENV REACT_APP_CONTENT_MAX_SIZE=5
ENV REACT_APP_PREVIEW_ACCEPTED_FILES=image/jpeg,image/png
ENV REACT_APP_PREVIEW_MAX_SIZE=1
ENV REACT_APP_MAPBOX_STYLE_URL=mapbox://styles/mapbox/streets-v11
ENV REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiZGFuaWVsZWd1aWRvdW5pIiwiYSI6ImNsMmVyOW5vazAyOXczaW8zYmJnOGczeWIifQ.R8HvtSP3S8gTlpkUeWq-BA
ENV REACT_APP_BACKGROUND_COLORS_PALETTE=#2E2E2E,#383838,#798774,#7A8988,#9E5646,#B58B50
ENV REACT_APP_TEXT_COLORS_PALETTE=#000,#FFF

RUN yarn build

FROM busybox:stable
WORKDIR /visual-editor
COPY --from=visual-editor-builder /visual-editor/build ./
